"""2025-01-29-16:45_initial_migration

Revision ID: 193cbbec6ea8
Revises: 
Create Date: 2025-01-29 16:45:13.028870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193cbbec6ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cax_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_cax_codes_id'), 'cax_codes', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('nurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_nurses_id'), 'nurses', ['id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_number', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('address', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('icd10_code', sa.String(), nullable=False),
    sa.Column('cax_code_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cax_code_id'], ['cax_codes.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_number')
    )
    op.create_index(op.f('ix_medical_histories_id'), 'medical_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_histories_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_nurses_id'), table_name='nurses')
    op.drop_table('nurses')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_cax_codes_id'), table_name='cax_codes')
    op.drop_table('cax_codes')
    # ### end Alembic commands ###
