"""2025-09-26-09:21_add_operation_remove_create_update

Revision ID: 301185d8499c
Revises: d3484eb9feba
Create Date: 2025-09-26 09:21:34.984021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301185d8499c'
down_revision: Union[str, None] = 'd3484eb9feba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
