"""2025-07-31-08:02_add_unque_constraint_history_number

Revision ID: 3ed1bd0e91ab
Revises: d1423d59e461
Create Date: 2025-07-31 08:06:13.211994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed1bd0e91ab'
down_revision: Union[str, None] = 'd1423d59e461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_history_number_admission_date', 'medical_histories', ['history_number', 'admission_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_history_number_admission_date', 'medical_histories', type_='unique')
    # ### end Alembic commands ###
