"""2025-10-09-08:02_delete_refined_diagnosis_medical_history

Revision ID: 4abe1671df48
Revises: 4e3d48bd42c1
Create Date: 2025-10-09 08:03:17.131074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abe1671df48'
down_revision: Union[str, None] = '4e3d48bd42c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_histories', 'refined_diagnosis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_histories', sa.Column('refined_diagnosis', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
