"""2025-10-09-07:38_add_patient_table

Revision ID: 4e3d48bd42c1
Revises: 506d32185f71
Create Date: 2025-10-09 07:38:53.554669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e3d48bd42c1'
down_revision: Union[str, None] = '506d32185f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.add_column('medical_histories', sa.Column('refined_diagnosis', sa.String(), nullable=True))
    op.add_column('medical_histories', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medical_histories', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('medical_histories', 'birth_date')
    op.drop_column('medical_histories', 'full_name')
    op.drop_column('medical_histories', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_histories', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medical_histories', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medical_histories', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medical_histories', type_='foreignkey')
    op.drop_column('medical_histories', 'patient_id')
    op.drop_column('medical_histories', 'refined_diagnosis')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
