"""2025-07-30-13:17_cax_correct

Revision ID: 5026e292a802
Revises: 193cbbec6ea8
Create Date: 2025-07-30 13:17:12.111325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5026e292a802'
down_revision: Union[str, None] = '193cbbec6ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cax_codes', sa.Column('cax_name', sa.Integer(), nullable=False))
    op.add_column('cax_codes', sa.Column('cax_code', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('cax_codes_full_name_key'), 'cax_codes', type_='unique')
    op.create_unique_constraint(None, 'cax_codes', ['cax_code'])
    op.create_unique_constraint(None, 'cax_codes', ['cax_name'])
    op.drop_column('cax_codes', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cax_codes', sa.Column('full_name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cax_codes', type_='unique')
    op.drop_constraint(None, 'cax_codes', type_='unique')
    op.create_unique_constraint(op.f('cax_codes_full_name_key'), 'cax_codes', ['full_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('cax_codes', 'cax_code')
    op.drop_column('cax_codes', 'cax_name')
    # ### end Alembic commands ###
