"""2025-09-26-09:35_correct_operations

Revision ID: 506d32185f71
Revises: c162faa26755
Create Date: 2025-09-26 09:36:02.459133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506d32185f71'
down_revision: Union[str, None] = 'c162faa26755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('medical_history_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'operations', 'medical_histories', ['medical_history_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'medical_history_id')
    # ### end Alembic commands ###
