"""2025-12-03-15:22_delete_unique_opername

Revision ID: 525f11b2c1f8
Revises: 595e8196188d
Create Date: 2025-12-03 15:23:02.416214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525f11b2c1f8'
down_revision: Union[str, None] = '595e8196188d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('operations_oper_name_key'), 'operations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('operations_oper_name_key'), 'operations', ['oper_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
