"""2025-07-31-06:34_add_medical_hystory_cancelled

Revision ID: 662046b2e993
Revises: 4539bbcace4c
Create Date: 2025-07-31 06:34:25.141382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662046b2e993'
down_revision: Union[str, None] = '4539bbcace4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_histories', sa.Column('cancelled', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_histories', 'cancelled')
    # ### end Alembic commands ###
