"""2025-08-06-16:42_add_is_active_and_days_cax

Revision ID: 68013df97df0
Revises: 4f6fe9245f0d
Create Date: 2025-08-06 16:42:50.189725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68013df97df0'
down_revision: Union[str, None] = '4f6fe9245f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cax_codes', sa.Column('quantity_of_days', sa.Integer(), nullable=False))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('nurses', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nurses', 'is_active')
    op.drop_column('doctors', 'is_active')
    op.drop_column('cax_codes', 'quantity_of_days')
    # ### end Alembic commands ###
