"""2025-07-31-07:36_change_history_number_ununique

Revision ID: d1423d59e461
Revises: 22aef59b6708
Create Date: 2025-07-31 07:36:49.346354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1423d59e461'
down_revision: Union[str, None] = '22aef59b6708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medical_histories_history_number_key'), 'medical_histories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('medical_histories_history_number_key'), 'medical_histories', ['history_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
